- name: Remove existing Volumes directories
  file:
    path: "{{ item }}"
    state: absent
    mode: 0777
  with_items:
    - /var/lib/osslm/volume-r00
    - /var/lib/osslm/volume-r01
    - /var/lib/osslm/volume-r02
    - /var/lib/osslm/volume-r03

- name: Create Volumes directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - /var/lib/osslm/volume-r00
    - /var/lib/osslm/volume-r01
    - /var/lib/osslm/volume-r02
    - /var/lib/osslm/volume-r03