- name: Check ansiblerm release in helm
  shell: helm get ansiblerm
  register: helm_get_arm
  failed_when: false
  changed_when: false

- name: Uninstall ansiblerm release
  shell: helm delete ansiblerm --purge
  when: helm_get_arm is not failed and helm_get_arm.rc == 0

- name: Remove Persistent Volume Claims
  shell: kubectl delete pvc -l release=ansiblerm
   
- name: Remove Persistent Volumes 
  shell: kubectl delete pv -l createdBy=osslm-ansible-rm
  
- name: Remove volume directories
  file:
    path: /var/lib/osslm/
    state: absent
  become: yes